# NOTE: This config is incomplete.
CHECKPOINT: ""

BODY_MODEL: SMPL

TRANSFORMER_ENCODER:
  NUM_HIDDEN_LAYERS: 4
  NUM_ATTENTION_HEADS: 4
  INPUT_FEAT_DIM: [2051, 512, 128]
  HIDDEN_FEAT_DIM: [1024, 256, 128]
  BERT_CONFIG_PATH: metro/modeling/bert/bert-base-uncased/
  DROPOUT_PROB: 0.1

BACKBONE:
