defaults:
  - model/metro_smpl
  - model/backbone/hrnet_w64
  - solver/sgd

WANDB:
  ENABLED: True
  DRYRUN: False
  PROJECT: metro
  TAGS: []

EVAL_ONLY: False

TEST:
  ENABLED: True
  EVAL_PERIOD: 2000
  ADDITIONAL_EVAL_STEPS: []

hydra:
  callbacks:
    wandb_callback:
      _target_: metro.utils.hydra.callbacks.WandbOutputDirCallback
    d2_logger_callback:
      _target_: metro.utils.hydra.callbacks.D2LoggerCallback
    download_ckpt_callback:
      _target_: metro.utils.hydra.callbacks.DownloadCkptCallback
  verbose: True



